"""Convert question_id to String in question_progress

Revision ID: 7b2431f05ea8
Revises: 988d47bb0b27
Create Date: 2025-06-12 01:53:08.475706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2431f05ea8'
down_revision = '988d47bb0b27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_progress', schema=None) as batch_op:
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('question_progress_question_id_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_progress', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('question_progress_question_id_fkey'), 'questions', ['question_id'], ['id'])
        batch_op.alter_column('question_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
