"""Add completed field to QuestionProgress

Revision ID: be19b29e8471
Revises: ebccf1d6e8d2
Create Date: 2025-06-17 23:52:41.045410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be19b29e8471'
down_revision = 'ebccf1d6e8d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('has_logged_in_before')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_logged_in_before', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    op.create_table('questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('choice_a', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('choice_b', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('choice_c', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('choice_d', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('correct_answer', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('chapter', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('explanation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('questions_pkey'))
    )
    # ### end Alembic commands ###
