"""Add completed column

Revision ID: ebccf1d6e8d2
Revises: fa6b0904b8ba
Create Date: 2025-06-17 22:24:32.034961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebccf1d6e8d2'
down_revision = 'fa6b0904b8ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_progress', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
