"""Add chapter column to QuestionProgress

Revision ID: fa6b0904b8ba
Revises: 06ab4d9b4a34
Create Date: 2025-06-17 19:28:35.949480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6b0904b8ba'
down_revision = '06ab4d9b4a34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chapter', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_progress', schema=None) as batch_op:
        batch_op.drop_column('chapter')

    # ### end Alembic commands ###
